Issue 6 create registration modal
codersforcauses/bluecrew pull request #31
Opened 2024-12-07 05:47 UTC by survivzhang

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2024-12-07 07:00 UTC, HuxleyBerry requested changes
Looks pretty good. I have a few comments though

2024-12-07 07:00 UTC, HuxleyBerry commented on client/src/components/RegisterModal.vue
> +const formData = reactive({
Can you use a ``ref`` instead of ``reactive`` here?

2024-12-07 07:00 UTC, HuxleyBerry commented on client/src/components/RegisterModal.vue
> +        <input
Can you use vuetify's ``v-text-field`` here instead? That will make the input fields look more consistent with the dropdowns.

2024-12-07 07:00 UTC, HuxleyBerry commented on client/src/components/RegisterModal.vue
> +  <div class="register-container">
I suggest using Vuetify's ``v-dialog`` component.

2024-12-07 07:00 UTC, HuxleyBerry commented on client/src/components/RegisterModal.vue
> +  <div class="register-container">
The modal is very narrow for me on mobile. If you use Vuetify's ``v-dialog`` component, you can use the ``fullscreen`` prop to make the modal fullscreen on mobile.

2024-12-11 06:27 UTC, HuxleyBerry requested changes

2024-12-11 06:27 UTC, HuxleyBerry commented on client/src/components/RegisterModal.vue
> +const vuetify = createVuetify({
``createVuetify()`` should only be done in ``App.vue``

2024-12-11 06:27 UTC, HuxleyBerry commented on client/src/components/RegisterModal.vue
> +import { VDateInput } from 'vuetify/labs/VDateInput'
Don't use components from Vuetify labs -- they aren't meant for production use (see https://vuetifyjs.com/en/labs/introduction/#what-is-labs). I think a standard input element with ``type="date"`` should be sufficient.

2024-12-14 04:55 UTC, HuxleyBerry requested changes
Looks good, just a few small requests.

2024-12-14 04:55 UTC, HuxleyBerry commented on client/src/components/RegisterModal.vue
> +const formData = ref({
Can you add a typescript type for this ref? I suggest defining this type in ``src/types/user.ts`` and import it here.

2024-12-14 04:55 UTC, HuxleyBerry commented on client/src/components/RegisterModal.vue
> +    <v-btn
Can you move this button out of the component? For demonstration purposes, you can put it in ``HomeView.vue`` instead.

2024-12-14 04:55 UTC, HuxleyBerry commented on client/src/components/RegisterModal.vue
> +      v-model="dialog"
We've now got a modal store which houses the state of which modal is open. That is in ``stores/modal.ts``. So the ``v-model`` should be bound to the state housed in the store instead.

2024-12-14 07:48 UTC, HuxleyBerry approved these changes
Great, LGTM

2024-12-14 07:48 UTC, aradavi63 commented
yippee

2024-12-14 07:48 UTC, merged