Added view for user model, urls for bingo and api, unit tests for the…
codersforcauses/bluecrew pull request #44
Opened 2024-12-14 06:22 UTC by MahitGtg

… view

## Change Summary
**views for the user model are set up as per the requirements of the client/src/types/users file**

### Change Form

- [x] The pull request title has an issue number 
- [ ] The change works by "Smoke testing" or quick testing
- [x] The change has tests
- [x] The change has documentation

2024-12-14 08:29 UTC, SafetyInObscurity requested changes, later dismissed
Looks good, just the tests need a tweak

2024-12-14 08:29 UTC, SafetyInObscurity commented on server/bingo/tests.py
> +        self.assertEqual(response.data["userName"], "testuser")
The rest of these assertions should match user_id, testing against the value of the model rather than a string

2024-12-14 14:28 UTC, MahitGtg commented on server/bingo/tests.py
> +        self.assertEqual(response.data["userName"], "testuser")
should be done now!

2024-12-15 08:49 UTC, HuxleyBerry approved these changes
LGTM

2025-01-04 03:34 UTC, merged